<?php

return [
    'site' => [
        'name' => 'Maharana Travels',
        'tagline' => 'Ride with Pride, Travel with Trust',
        'phone' => '+91 9416198045',
        'phone_raw' => '919416198045',
        'email' => 'maharanatravels0001@gmail.com',
        'address' => 'Maharana Travels, Shop No 7, Juneja Square, Highland Marg, Zirakpur, Nabha, Punjab 140603',
        'cta_title' => 'Book Online Today And Travel In Comfort',
        'cta_subtitle' => 'On Your Next Trip',
        'about' => 'Maharana Travels is your trusted partner for reliable and comfortable transportation across North India. We provide airport transfers, outstation cabs, local sightseeing, and wedding car rentals with verified drivers and transparent fares.',
    ],
    'routes' => [
        ['from' => 'Chandigarh', 'to' => 'Delhi', 'price' => 3000, 'url' => 'chandigarh-to-delhi'],
        ['from' => 'Zirakpur', 'to' => 'Gurgaon', 'price' => 4000, 'url' => 'zirakpur-to-gurgaon'],
        ['from' => 'Zirakpur', 'to' => 'Delhi Airport', 'price' => 4000, 'url' => 'zirakpur-to-delhi-airport'],
        ['from' => 'Chandigarh', 'to' => 'Ambala', 'price' => 1800, 'url' => 'chandigarh-to-ambala'],
        ['from' => 'Chandigarh', 'to' => 'Pathankot', 'price' => 3500, 'url' => 'chandigarh-to-pathankot'],
        ['from' => 'Kharar', 'to' => 'Jalandhar', 'price' => 2500, 'url' => 'kharar-to-jalandhar'],
        ['from' => 'Kharar', 'to' => 'Delhi', 'price' => 3000, 'url' => 'kharar-to-delhi'],
        ['from' => 'Pathankot', 'to' => 'Chandigarh', 'price' => 3500, 'url' => 'pathankot-to-chandigarh'],
        ['from' => 'Mohali', 'to' => 'Patiala', 'price' => 1200, 'url' => 'mohali-to-patiala'],
        ['from' => 'Kharar', 'to' => 'Noida', 'price' => 3500, 'url' => 'kharar-to-noida'],
        ['from' => 'Chandigarh Airport', 'to' => 'Shimla', 'price' => 2500, 'url' => 'chandigarh-to-shimla'],
        ['from' => 'Chandigarh', 'to' => 'Manali', 'price' => 4500, 'url' => 'chandigarh-to-manali'],
        ['from' => 'Chandigarh', 'to' => 'Ghaziabad', 'price' => 3500, 'url' => 'chandigarh-to-ghaziabad'],
        ['from' => 'Chandigarh', 'to' => 'Noida', 'price' => 3500, 'url' => 'chandigarh-to-noida'],
        ['from' => 'Chandigarh', 'to' => 'Ludhiana', 'price' => 1500, 'url' => 'chandigarh-to-ludhiana'],
        ['from' => 'Amritsar', 'to' => 'Chandigarh', 'price' => 3000, 'url' => 'amritsar-to-chandigarh'],
    ],
    'destinations' => [
        ['name' => 'Chandigarh to Shimla Tour', 'img' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'],
        ['name' => 'Delhi to Manali Tour', 'img' => 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop'],
        ['name' => 'Chandigarh to Manali Tour', 'img' => 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=600&fit=crop'],
        ['name' => 'Delhi to Amritsar Tour', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Complete_view_of_Golden_Temple_complex_09.jpg'],
        ['name' => 'Chandigarh to Haridwar Tour', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Evening_view_of_Har-ki-Pauri%2C_Haridwar.jpg'],
        ['name' => 'Delhi to Rishikesh Tour', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/7/75/Rishikesh-Lakshman_Jhula_by_Kaustubh_Nayyar.jpg'],
    ],
    'advantages' => [
        ['icon' => 'fa-shield-alt', 'title' => '100% Safe', 'desc' => 'Verified drivers and well-maintained vehicles for your peace of mind.'],
        ['icon' => 'fa-balance-scale', 'title' => 'Price Transparency', 'desc' => 'No hidden charges. Clear and upfront pricing for all services.'],
        ['icon' => 'fa-clock', 'title' => '24x7 Cab Service', 'desc' => 'Round the clock availability. Book a cab anytime, anywhere.'],
        ['icon' => 'fa-ban', 'title' => 'Zero Cancellation', 'desc' => 'Cancel anytime without fees. Flexible booking options for you.'],
        ['icon' => 'fa-map-marker-alt', 'title' => 'GPS Enabled Cars', 'desc' => 'All vehicles equipped with GPS for real-time location monitoring.'],
        ['icon' => 'fa-spray-can', 'title' => 'Neat And Clean', 'desc' => 'Well-maintained and sanitized vehicles for a hygienic journey.'],
        ['icon' => 'fa-car-crash', 'title' => 'Fully Insured', 'desc' => 'Comprehensive insurance coverage for all vehicles.'],
        ['icon' => 'fa-headset', 'title' => 'Customer Service', 'desc' => 'Dedicated support team available 24/7 to assist you.'],
    ],
    'faqs' => [
        ['q' => 'How do I book a cab online?', 'a' => 'Fill out the booking form with pickup, destination, date and time, then click Search Cabs and choose your vehicle.'],
        ['q' => 'What payment methods do you accept?', 'a' => 'Cash, credit/debit cards, UPI, net banking, and digital wallets.'],
        ['q' => 'Can I cancel my booking?', 'a' => 'Yes, cancel anytime without cancellation fees before 6 hours of the trip.'],
        ['q' => 'Are your drivers verified and licensed?', 'a' => 'Yes, all drivers are verified, licensed, and experienced with background checks.'],
        ['q' => 'Do you provide outstation taxi services?', 'a' => 'Yes, we provide outstation taxi services across North India with one-way and round-trip options.'],
        ['q' => 'What types of vehicles are available?', 'a' => 'We offer sedans, SUVs, Crysta, Hycross, Kia Carens, and tempo travellers.'],
        ['q' => 'Is there 24/7 customer support?', 'a' => 'Yes, you can reach us anytime by call or WhatsApp for immediate help.'],
        ['q' => 'Are your vehicles GPS enabled?', 'a' => 'Yes, all vehicles have GPS for real-time tracking and added safety.'],
    ],
    'cities' => [
        'Delhi', 'Mumbai', 'Chandigarh', 'Amritsar', 'Ludhiana', 'Shimla', 'Manali',
        'Mohali', 'Patiala', 'Jalandhar', 'Pathankot', 'Kharar', 'Zirakpur', 'Noida',
        'Gurgaon', 'Haridwar', 'Rishikesh', 'Dehradun', 'Ambala', 'Ghaziabad', 'Delhi Airport', 'Ramgarh',
        'Jammu', 'Jaipur',
    ],
    'route_prices' => [
        [
            'from' => 'Delhi',
            'to' => 'Chandigarh',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Dzire', 'oneway' => 3000, 'round_trip' => 6000],
                ['car_name' => 'Ertiga', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Crysta', 'oneway' => 5000, 'round_trip' => 10000],
                ['car_name' => 'Kia Carens', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Hycross', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Force Traveller', 'oneway' => 12000, 'round_trip' => 16000],
                ['car_name' => 'Force Urbania', 'oneway' => 15000, 'round_trip' => 18000],
            ],
        ],
        [
            'from' => 'Gurgaon',
            'to' => 'Chandigarh',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Dzire', 'oneway' => 3500, 'round_trip' => 6500],
                ['car_name' => 'Ertiga', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Crysta', 'oneway' => 5500, 'round_trip' => 10500],
                ['car_name' => 'Kia Carens', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Hycross', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Force Traveller', 'oneway' => 15000, 'round_trip' => 17000],
                ['car_name' => 'Force Urbania', 'oneway' => 17000, 'round_trip' => 19000],
            ],
        ],
        [
            'from' => 'Noida',
            'to' => 'Chandigarh',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Dzire', 'oneway' => 3500, 'round_trip' => 6500],
                ['car_name' => 'Ertiga', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Crysta', 'oneway' => 5500, 'round_trip' => 10500],
                ['car_name' => 'Kia Carens', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Hycross', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Force Traveller', 'oneway' => 15000, 'round_trip' => 17000],
                ['car_name' => 'Force Urbania', 'oneway' => 17000, 'round_trip' => 19000],
            ],
        ],
        [
            'from' => 'Kharar',
            'to' => 'Noida',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Dzire', 'oneway' => 3500, 'round_trip' => 6500],
                ['car_name' => 'Ertiga', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Crysta', 'oneway' => 5500, 'round_trip' => 10500],
                ['car_name' => 'Kia Carens', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Hycross', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Force Traveller', 'oneway' => 15000, 'round_trip' => 17000],
                ['car_name' => 'Force Urbania', 'oneway' => 17000, 'round_trip' => 19000],
            ],
        ],
        [
            'from' => 'Zirakpur',
            'to' => 'Gurgaon',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Dzire', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Ertiga', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Crysta', 'oneway' => 5500, 'round_trip' => 10500],
                ['car_name' => 'Kia Carens', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Hycross', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Force Traveller', 'oneway' => 15000, 'round_trip' => 17000],
                ['car_name' => 'Force Urbania', 'oneway' => 17000, 'round_trip' => 19000],
            ],
        ],
        [
            'from' => 'Zirakpur',
            'to' => 'Delhi Airport',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Dzire', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Ertiga', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Crysta', 'oneway' => 5500, 'round_trip' => 10500],
                ['car_name' => 'Kia Carens', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Hycross', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Force Traveller', 'oneway' => 15000, 'round_trip' => 17000],
                ['car_name' => 'Force Urbania', 'oneway' => 17000, 'round_trip' => 19000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Ambala',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 2000, 'round_trip' => 3500],
                ['car_name' => 'Dzire', 'oneway' => 1800, 'round_trip' => 3000],
                ['car_name' => 'Ertiga', 'oneway' => 2000, 'round_trip' => 3500],
                ['car_name' => 'Crysta', 'oneway' => 3000, 'round_trip' => 5500],
                ['car_name' => 'Kia Carens', 'oneway' => 2500, 'round_trip' => 4500],
                ['car_name' => 'Hycross', 'oneway' => 2500, 'round_trip' => 4500],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Pathankot',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Dzire', 'oneway' => 3500, 'round_trip' => 6500],
                ['car_name' => 'Ertiga', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Crysta', 'oneway' => 5000, 'round_trip' => 10000],
                ['car_name' => 'Kia Carens', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Hycross', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Force Traveller', 'oneway' => 12000, 'round_trip' => 16000],
                ['car_name' => 'Force Urbania', 'oneway' => 15000, 'round_trip' => 18000],
            ],
        ],
        [
            'from' => 'Kharar',
            'to' => 'Jalandhar',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 3000, 'round_trip' => 5500],
                ['car_name' => 'Dzire', 'oneway' => 2500, 'round_trip' => 4500],
                ['car_name' => 'Ertiga', 'oneway' => 3000, 'round_trip' => 5500],
                ['car_name' => 'Crysta', 'oneway' => 4500, 'round_trip' => 8000],
                ['car_name' => 'Kia Carens', 'oneway' => 3500, 'round_trip' => 6000],
                ['car_name' => 'Hycross', 'oneway' => 3500, 'round_trip' => 6000],
                ['car_name' => 'Force Traveller', 'oneway' => 10000, 'round_trip' => 13000],
                ['car_name' => 'Force Urbania', 'oneway' => 14000, 'round_trip' => 15000],
            ],
        ],
        [
            'from' => 'Kharar',
            'to' => 'Delhi',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Dzire', 'oneway' => 3000, 'round_trip' => 6000],
                ['car_name' => 'Ertiga', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Crysta', 'oneway' => 5000, 'round_trip' => 10000],
                ['car_name' => 'Kia Carens', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Hycross', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Force Traveller', 'oneway' => 12000, 'round_trip' => 16000],
                ['car_name' => 'Force Urbania', 'oneway' => 15000, 'round_trip' => 18000],
            ],
        ],
        [
            'from' => 'Mohali',
            'to' => 'Patiala',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 1500, 'round_trip' => 3000],
                ['car_name' => 'Dzire', 'oneway' => 1200, 'round_trip' => 2000],
                ['car_name' => 'Ertiga', 'oneway' => 1500, 'round_trip' => 3000],
                ['car_name' => 'Crysta', 'oneway' => 2500, 'round_trip' => 5000],
                ['car_name' => 'Kia Carens', 'oneway' => 2000, 'round_trip' => 3000],
                ['car_name' => 'Hycross', 'oneway' => 2000, 'round_trip' => 3000],
            ],
        ],
        [
            'from' => 'Chandigarh Airport',
            'to' => 'Shimla',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 3000, 'round_trip' => 5000],
                ['car_name' => 'Dzire', 'oneway' => 2500, 'round_trip' => 4500],
                ['car_name' => 'Ertiga', 'oneway' => 3000, 'round_trip' => 5000],
                ['car_name' => 'Crysta', 'oneway' => 4500, 'round_trip' => 8000],
                ['car_name' => 'Kia Carens', 'oneway' => 3500, 'round_trip' => 6000],
                ['car_name' => 'Hycross', 'oneway' => 3500, 'round_trip' => 6000],
                ['car_name' => 'Force Traveller', 'oneway' => 10000, 'round_trip' => 13000],
                ['car_name' => 'Force Urbania', 'oneway' => 14000, 'round_trip' => 15000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Ghaziabad',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Dzire', 'oneway' => 3500, 'round_trip' => 6500],
                ['car_name' => 'Ertiga', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Crysta', 'oneway' => 5500, 'round_trip' => 10500],
                ['car_name' => 'Kia Carens', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Hycross', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Force Traveller', 'oneway' => 15000, 'round_trip' => 17000],
                ['car_name' => 'Force Urbania', 'oneway' => 17000, 'round_trip' => 19000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Shimla',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 3000, 'round_trip' => 5000],
                ['car_name' => 'Dzire', 'oneway' => 2000, 'round_trip' => 4000],
                ['car_name' => 'Ertiga', 'oneway' => 3000, 'round_trip' => 5000],
                ['car_name' => 'Crysta', 'oneway' => 4500, 'round_trip' => 8000],
                ['car_name' => 'Kia Carens', 'oneway' => 3500, 'round_trip' => 6000],
                ['car_name' => 'Hycross', 'oneway' => 3500, 'round_trip' => 6000],
                ['car_name' => 'Force Traveller', 'oneway' => 10000, 'round_trip' => 13000],
                ['car_name' => 'Force Urbania', 'oneway' => 14000, 'round_trip' => 15000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Manali',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Dzire', 'oneway' => 4500, 'round_trip' => 7000],
                ['car_name' => 'Ertiga', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Crysta', 'oneway' => 6000, 'round_trip' => 12000],
                ['car_name' => 'Kia Carens', 'oneway' => 5500, 'round_trip' => 10500],
                ['car_name' => 'Hycross', 'oneway' => 5500, 'round_trip' => 10500],
                ['car_name' => 'Force Traveller', 'oneway' => 17000, 'round_trip' => 20000],
                ['car_name' => 'Force Urbania', 'oneway' => 18000, 'round_trip' => 22000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Dehradun',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Dzire', 'oneway' => 3000, 'round_trip' => 6000],
                ['car_name' => 'Ertiga', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Crysta', 'oneway' => 5000, 'round_trip' => 10000],
                ['car_name' => 'Kia Carens', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Hycross', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Force Traveller', 'oneway' => 12000, 'round_trip' => 16000],
                ['car_name' => 'Force Urbania', 'oneway' => 15000, 'round_trip' => 18000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Patiala',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 1500, 'round_trip' => 3000],
                ['car_name' => 'Dzire', 'oneway' => 1200, 'round_trip' => 2000],
                ['car_name' => 'Ertiga', 'oneway' => 1500, 'round_trip' => 3000],
                ['car_name' => 'Crysta', 'oneway' => 2500, 'round_trip' => 5000],
                ['car_name' => 'Kia Carens', 'oneway' => 2000, 'round_trip' => 3000],
                ['car_name' => 'Hycross', 'oneway' => 2000, 'round_trip' => 3000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Amritsar',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Dzire', 'oneway' => 3000, 'round_trip' => 6000],
                ['car_name' => 'Ertiga', 'oneway' => 4000, 'round_trip' => 7000],
                ['car_name' => 'Crysta', 'oneway' => 5000, 'round_trip' => 10000],
                ['car_name' => 'Kia Carens', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Hycross', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Force Traveller', 'oneway' => 12000, 'round_trip' => 16000],
                ['car_name' => 'Force Urbania', 'oneway' => 15000, 'round_trip' => 18000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Jammu',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 5000, 'round_trip' => 9500],
                ['car_name' => 'Dzire', 'oneway' => 4000, 'round_trip' => 7500],
                ['car_name' => 'Ertiga', 'oneway' => 5000, 'round_trip' => 9500],
                ['car_name' => 'Crysta', 'oneway' => 6500, 'round_trip' => 11500],
                ['car_name' => 'Kia Carens', 'oneway' => 6000, 'round_trip' => 10500],
                ['car_name' => 'Hycross', 'oneway' => 6000, 'round_trip' => 10500],
                ['car_name' => 'Force Traveller', 'oneway' => 14000, 'round_trip' => 18000],
                ['car_name' => 'Force Urbania', 'oneway' => 16000, 'round_trip' => 25000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Haridwar',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Dzire', 'oneway' => 3500, 'round_trip' => 6500],
                ['car_name' => 'Ertiga', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Crysta', 'oneway' => 5500, 'round_trip' => 10500],
                ['car_name' => 'Kia Carens', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Hycross', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Force Traveller', 'oneway' => 13000, 'round_trip' => 17000],
                ['car_name' => 'Force Urbania', 'oneway' => 16000, 'round_trip' => 19000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Rishikesh',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Dzire', 'oneway' => 3500, 'round_trip' => 6500],
                ['car_name' => 'Ertiga', 'oneway' => 4500, 'round_trip' => 7500],
                ['car_name' => 'Crysta', 'oneway' => 5500, 'round_trip' => 10500],
                ['car_name' => 'Kia Carens', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Hycross', 'oneway' => 5000, 'round_trip' => 8000],
                ['car_name' => 'Force Traveller', 'oneway' => 13000, 'round_trip' => 17000],
                ['car_name' => 'Force Urbania', 'oneway' => 16000, 'round_trip' => 19000],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Ludhiana',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 2000, 'round_trip' => 4000],
                ['car_name' => 'Dzire', 'oneway' => 1500, 'round_trip' => 3000],
                ['car_name' => 'Ertiga', 'oneway' => 2000, 'round_trip' => 4000],
                ['car_name' => 'Crysta', 'oneway' => 3000, 'round_trip' => 5000],
                ['car_name' => 'Kia Carens', 'oneway' => 2500, 'round_trip' => 4500],
                ['car_name' => 'Hycross', 'oneway' => 2500, 'round_trip' => 4500],
            ],
        ],
        [
            'from' => 'Chandigarh',
            'to' => 'Jaipur',
            'prices' => [
                ['car_name' => 'Rumion', 'oneway' => 6500, 'round_trip' => 12000],
                ['car_name' => 'Dzire', 'oneway' => 5000, 'round_trip' => 9500],
                ['car_name' => 'Ertiga', 'oneway' => 6500, 'round_trip' => 9500],
                ['car_name' => 'Crysta', 'oneway' => 8000, 'round_trip' => 14000],
                ['car_name' => 'Kia Carens', 'oneway' => 6500, 'round_trip' => 12000],
                ['car_name' => 'Hycross', 'oneway' => 6500, 'round_trip' => 12000],
            ],
        ],
    ],
    'cabs' => [
        [
            'id' => 2,
            'name' => 'Maruti Suzuki Dzire',
            'type' => 'Sedan',
            'seats' => 4,
            'bags' => 2,
            'rate_base' => 10,
            'rate_extra' => 13,
            'fuel' => 'CNG/Petrol/Diesel',
            'image' => '/images/maruti_suzuki_dzire_1771750729.webp',
            'price_per_km' => 10,
            'ac' => true,
        ],
        [
            'id' => 3,
            'name' => 'Maruti Suzuki Ertiga',
            'type' => 'SUV',
            'seats' => 6,
            'bags' => 4,
            'rate_base' => 14,
            'rate_extra' => 17,
            'fuel' => 'CNG/Petrol/Diesel',
            'image' => '/images/maruti_suzuki_ertiga_1771750612.webp',
            'price_per_km' => 14,
            'ac' => true,
        ],
        [
            'id' => 4,
            'name' => 'Toyota Innova Crysta',
            'type' => 'SUV',
            'seats' => 7,
            'bags' => 6,
            'rate_base' => 17,
            'rate_extra' => 20,
            'fuel' => 'CNG/Petrol/Diesel',
            'image' => '/images/toyota_innova_crysta_1771750253.webp',
            'price_per_km' => 17,
            'ac' => true,
        ],
        [
            'id' => 5,
            'name' => 'Kia Carens',
            'type' => 'SUV',
            'seats' => 6,
            'bags' => 5,
            'rate_base' => 15,
            'rate_extra' => 18,
            'fuel' => 'CNG/Petrol/Diesel',
            'image' => '/images/kia_carens_1771750815.webp',
            'price_per_km' => 15,
            'ac' => true,
        ],
        [
            'id' => 6,
            'name' => 'Toyota Hycross',
            'type' => 'SUV',
            'seats' => 7,
            'bags' => 6,
            'rate_base' => 20,
            'rate_extra' => 23,
            'fuel' => 'CNG/Petrol/Diesel',
            'image' => '/images/hy_cross_1771752033.webp',
            'price_per_km' => 20,
            'ac' => true,
        ],
        [
            'id' => 7,
            'name' => 'Force Traveller',
            'type' => 'Tempo Traveller',
            'seats' => 12,
            'bags' => 10,
            'rate_base' => 28,
            'rate_extra' => 31,
            'fuel' => 'Diesel',
            'image' => '/images/force_1771751829.webp',
            'price_per_km' => 28,
            'ac' => true,
        ],
        [
            'id' => 8,
            'name' => 'Force Urbania',
            'type' => 'Tempo Traveller',
            'seats' => 17,
            'bags' => 12,
            'rate_base' => 35,
            'rate_extra' => 38,
            'fuel' => 'Diesel',
            'image' => '/images/force_urbania_1771751732.webp',
            'price_per_km' => 35,
            'ac' => true,
        ],
    ],
    'services' => [
        ['id' => 19, 'title' => 'Chandigarh to Delhi Taxi | One Way & Round Trip Cab', 'slug' => 'chandigarh-to-delhi', 'from' => 'Chandigarh', 'to' => 'Delhi', 'km' => 245],
        ['id' => 1, 'title' => 'Delhi to Shimla Taxi | Cheap & Reliable Cab', 'slug' => 'delhi-to-shimla', 'from' => 'Delhi', 'to' => 'Shimla', 'km' => 345],
        ['id' => 2, 'title' => 'Delhi to Kasol Taxi | One Way & Round Trip Cabs', 'slug' => 'delhi-to-kasol', 'from' => 'Delhi', 'to' => 'Kasol', 'km' => 520],
        ['id' => 3, 'title' => 'Gurgaon to Manali Taxi | One Way & Round Trip', 'slug' => 'gurgaon-to-manali', 'from' => 'Gurgaon', 'to' => 'Manali', 'km' => 550],
        ['id' => 4, 'title' => 'Delhi to Manali Taxi | Book One Way Cab at Best Price', 'slug' => 'delhi-to-manali', 'from' => 'Delhi', 'to' => 'Manali', 'km' => 572],
        ['id' => 5, 'title' => 'Gurgaon to Kharar Taxi | One Way & Round Trip', 'slug' => 'gurgaon-to-kharar', 'from' => 'Gurgaon', 'to' => 'Kharar', 'km' => 265],
        ['id' => 6, 'title' => 'Gurgaon to Panchkula Taxi | Best Price Cab', 'slug' => 'gurgaon-to-panchkula', 'from' => 'Gurgaon', 'to' => 'Panchkula', 'km' => 270],
        ['id' => 7, 'title' => 'Gurgaon to Mohali Taxi | Best Price Cab Service', 'slug' => 'gurgaon-to-mohali', 'from' => 'Gurgaon', 'to' => 'Mohali', 'km' => 265],
        ['id' => 8, 'title' => 'Gurgaon to Chandigarh Taxi | One Way Cab', 'slug' => 'gurgaon-to-chandigarh', 'from' => 'Gurgaon', 'to' => 'Chandigarh', 'km' => 265],
        ['id' => 9, 'title' => 'Gurgaon to Zirakpur Taxi | One Way Cab', 'slug' => 'gurgaon-to-zirakpur', 'from' => 'Gurgaon', 'to' => 'Zirakpur', 'km' => 258],
        ['id' => 10, 'title' => 'Delhi Airport to Patiala Taxi | Best Price', 'slug' => 'delhi-airport-to-patiala', 'from' => 'Delhi Airport', 'to' => 'Patiala', 'km' => 320],
        ['id' => 11, 'title' => 'Delhi Airport to Amritsar Cab | One Way Taxi', 'slug' => 'delhi-airport-to-amritsar', 'from' => 'Delhi Airport', 'to' => 'Amritsar', 'km' => 460],
        ['id' => 12, 'title' => 'Delhi Airport to Jalandhar Taxi | Sedan & SUV', 'slug' => 'delhi-airport-to-jalandhar', 'from' => 'Delhi Airport', 'to' => 'Jalandhar', 'km' => 390],
        ['id' => 13, 'title' => 'Chandigarh to Shimla Taxi | Best Fare Cab', 'slug' => 'chandigarh-to-shimla', 'from' => 'Chandigarh', 'to' => 'Shimla', 'km' => 115],
        ['id' => 14, 'title' => 'Amritsar to Chandigarh Cab | One Way Taxi', 'slug' => 'amritsar-to-chandigarh', 'from' => 'Amritsar', 'to' => 'Chandigarh', 'km' => 220],
        ['id' => 15, 'title' => 'Mohali to Patiala Taxi | Affordable Cab Service', 'slug' => 'mohali-to-patiala', 'from' => 'Mohali', 'to' => 'Patiala', 'km' => 65],
        ['id' => 16, 'title' => 'Chandigarh to Ludhiana Cab | Outstation Taxi', 'slug' => 'chandigarh-to-ludhiana', 'from' => 'Chandigarh', 'to' => 'Ludhiana', 'km' => 100],
        ['id' => 17, 'title' => 'Kharar to Delhi Taxi | One Way Cab', 'slug' => 'kharar-to-delhi', 'from' => 'Kharar', 'to' => 'Delhi', 'km' => 270],
        ['id' => 18, 'title' => 'Chandigarh to Manali Taxi | Hill Station Cab', 'slug' => 'chandigarh-to-manali', 'from' => 'Chandigarh', 'to' => 'Manali', 'km' => 310],
    ],
];
